name: Azure Login and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-web-app-name'
          slot-name: 'your-slot-name'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
